-- SQLite migration 0001: Create users table
-- UUID PRIMARY KEY — generated by Rust, never by the DB.
-- TIMESTAMPTZ → TEXT (ISO 8601 UTC string).

CREATE TABLE IF NOT EXISTS users (
    id            TEXT         PRIMARY KEY,
    email         TEXT         UNIQUE NOT NULL,
    password_hash TEXT         NOT NULL,
    name          TEXT         NOT NULL,
    created_at    TEXT         NOT NULL DEFAULT (datetime('now')),
    updated_at    TEXT         NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
